version: 2
executorType: docker
containerInfo:
  - image: underwaterpony/centos:20171211
stages:
  build:
    workDir: ~/dynamodb-lambda-autoscale
    steps:
      - type: checkout

      - type: deploy
        name: serverless deploy
        command: |
          npm install
          npm run build
          serverless deploy -v
