service: dynamodb-lambda-autoscale

frameworkVersion: ">=1.20.0"

plugins:
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2
  versionFunctions: true
  role: arn:aws:iam::188664007186:role/dynamodb-autoscale-lambda-role
  memorySize: 512
  timeout: 50
  deploymentBucket: unific-lambdas

package:
  artifact: dist.zip

functions:
  dynamodb-lambda-autoscale:
    handler: index.handler
    name: ${self:service}
    description: Monitors DynamoDB table consumed capacity and throttles and dynamically scales provisioned capacity
    events:
      - schedule:
          rate: rate(1 minute)

custom:
  notifications:
    - protocol: sns
      endpoint: arn:aws:sns:${self:provider.region}:188664007186:UnificOpsTeam

  alerts:
    topics:
      alarm:
        topic: ${self:service}-alerts-alarm
        notifications: ${self:custom.notifications}
    global:
      - functionThrottles

  prune:
    automatic: true
    number: 5
